version: '2.1'

services:
  postgres-denis:
    image: postgres:12.0
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - .:/data/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis
    ports:
      - "6379:6379"